# Generated by Django 2.2.4 on 2019-08-17 17:46

from django.db import migrations
import phonenumbers

def fill_owner_phone_pure(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(number):
            flat.owner_phone_pure = number
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20190817_2043'),
    ]

    operations = [
        migrations.RunPython(fill_owner_phone_pure),
    ]
