# Generated by Django 2.2.4 on 2019-08-18 05:38

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist

def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        try:
            owner = Owner.objects.get(fio=flat.owner)
            owner.flats.add(flat)

        except ObjectDoesNotExist:
            owner = Owner.objects.create(
                fio=flat.owner,
                phonenumber=flat.owners_phonenumber,
                phone_pure=flat.owner_phone_pure,
            )
            owner.save()
            owner.flats.add(flat)
            owner.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owners)
    ]
